// lib/auto_version.dart
// 
// NOTE: This file is auto-generated by update_version.dart
// The SINGLE SOURCE OF TRUTH for version is AppConfig in core/config/app_config.dart
// This file exists for build automation compatibility.
import 'package:flutter/foundation.dart';
import '../core/config/app_config.dart';

class AppVersion {
  // Delegate to AppConfig - the single source of truth
  static String get version => AppConfig.appVersion;
  static String get buildNumber => AppConfig.buildNumber;
  static String get buildDate => AppConfig.buildDate;
  
  static String get fullVersion => AppConfig.fullVersion;
  
  static void logVersion() {
    AppConfig.logConfig();
  }
}